# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:7.7.4

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - mysql:5.5.54
  
variables:
  MYSQL_DATABASE: bibliotouch
  MYSQL_USER: bibliotouch
  MYSQL_PASSWORD: bibliotouch


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - bibliotouch-server/node_modules/
  - mapgrid-js/node_modules/

run_server:
  script:
   - npm --prefix ./bibliotouch-server/ install
   - npm --prefix ./bibliotouch-server/ start
   
build_mapgrid:
  script:
   - npm --prefix ./mapgrid-js/ install
   - npm --prefix ./mapgrid-js/ run build