# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:7.9.0
  
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: test
  MYSQL_USER: bibliotouch
  MYSQL_PASSWORD: bibliotouch

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - bibliotouch-server/node_modules/
  - mapgrid-js/node_modules/

before_script:
  - apt-get update
  - apt-get install -y mysql-client libmysqlclient-dev

test_basic_server_running:
  services:
    - mysql:5.7
  script:
   - export NODE_ENV=ci
   - mysql < ./bibliotouch-server/test/biblioitems-100.sql -u root -proot --host=mysql
   - npm --prefix ./bibliotouch-server/ install
   - npm --prefix ./bibliotouch-server/ run flush
   - npm --prefix ./bibliotouch-server/ test
   
build_mapgrid:
  script:
   - npm --prefix ./mapgrid-js/ install
   - npm --prefix ./mapgrid-js/ run build