# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:7.7.4
  
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: bibliotouch
  MYSQL_USER: bibliotouch
  MYSQL_PASSWORD: bibliotouch

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - bibliotouch-server/node_modules/
  - mapgrid-js/node_modules/

test_basic_server_running:
  services:
    - mysql:5.5.54
  script:
   - export NODE_ENV=ci
   - npm --prefix ./bibliotouch-server/ install
   - npm --prefix ./bibliotouch-server/ test
   
build_mapgrid:
  script:
   - npm --prefix ./mapgrid-js/ install
   - npm --prefix ./mapgrid-js/ run build